version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      BACKEND_STORE_URI: /mlflow/mlruns
      ARTIFACT_ROOT: /mlflow/artifacts
    volumes:
      - ./mlflow:/mlflow
    command: >
      mlflow server
        --backend-store-uri /mlflow/mlruns
        --default-artifact-root /mlflow/artifacts
        --host 0.0.0.0
        --port 5000
